local nl = require("nattlua.compiler")
local profiler = require("nattlua.other.profiler")
local code = io.open("/home/caps/projects/NattLua/examples/projects/gmod/nattlua/glua_base.nlua", "r"):read("*all")
--code = "local SERVER = true\nlocal CLIENT = true\nlocal MENU = true\n" .. code
local c = nl.New(code)
c:Parse()
profiler.Start(true)
c:Analyze()
c:Analyze()
c:Analyze()
c:Analyze()
c:Analyze()
c:Analyze()
c:Analyze()
profiler.Stop(true)