name: build
on: [push]

jobs:
  nattlua:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Build LuaJIT 
        run: |
          nix develop --command bash -c "which luajit && luajit -v"
      
      - name: Run nattlua tests
        run: |
          nix develop --command bash -c "luajit nattlua.lua test"
      
      - name: Build nattlua
        run: |
          nix develop --command bash -c "luajit nattlua.lua build"
          # Rename to nattlua.lua
          rm nattlua.lua # remove the original nattlua.lua file first
          mv build_output.lua nattlua.lua


      - name: Upload nattlua.lua
        uses: actions/upload-artifact@v4
        with:
          name: nattlua          
          path: nattlua.lua

  web-playground:
    runs-on: ubuntu-latest
    needs: nattlua
    if: github.ref == 'refs/heads/master'

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd web_playground
          yarn install

      - name: Build web playground
        run: |
          cd web_playground
          nix develop --command bash -c "node build.js"

      - name: Deploy to GitHub Pages
        run: |
          cd web_playground/public
          git init
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all --force
          git commit -m "Deploy web playground"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}