name: build
on: [push]

jobs:
  nattlua:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: checkout latest luajit 2.1
        uses: actions/checkout@v4
        with:
          repository: LuaJIT/LuaJIT
          ref: v2.1
          path: luajit

      - name: build and install luajit
        run: cd luajit && make && sudo make install && cd ..

      - name: run nattlua tests
        run: luajit nattlua.lua test

      - name: build nattlua to build_output.lua and run tests with it
        run: luajit nattlua.lua build

      - name: replace nattlua.lua with build_output.lua for upload
        run: rm nattlua.lua && mv build_output.lua nattlua.lua

      - name: upload nattlua.lua
        uses: actions/upload-artifact@v4
        with:
          name: nattlua          
          path: nattlua.lua