name: build
on: [push]

jobs:
  nattlua:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the project
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Build LuaJIT 
        run: |
          nix develop --command bash -c "which luajit && luajit -v"
      
      - name: Run nattlua tests
        run: |
          nix develop --command bash -c "luajit nattlua.lua test"
      
      - name: Build nattlua
        run: |
          nix develop --command bash -c "luajit nattlua.lua build"

      - name: Upload nattlua.lua
        uses: actions/upload-artifact@v4
        with:
          name: nattlua          
          path: build_output.lua