name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: test
        run: |
          sudo ln -sf luajit-2.1.0-beta3 /home/runner/work/NattLua/NattLua/.lua/bin/luajit
          luajit test/run.lua
