name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout latest luajit 2.1
        uses: actions/checkout@master
        with:
          repository: LuaJIT/LuaJIT
          ref: v2.1
          path: luajit

      - name: build luajit
        run: cd luajit && make && make install

      - name: test
        run: luajit test/run.lua
